name: code_note
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_code_editor: ^0.3.5
  flutter_highlight: ^0.7.0
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  flutter_svg: ^2.2.3
  highlight: ^0.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  riverpod: ^3.0.3
  shamsi_date: ^1.1.1
  uuid: ^4.5.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/brand/codenote_logo.png
    - assets/brand/logo_transparent.png
    - assets/img/card_bg.png
    - assets/img/notepad.png

    - assets/languages/c++.png
    - assets/languages/css.png
    - assets/languages/dart.png
    - assets/languages/go.png
    - assets/languages/html.png
    - assets/languages/java.png
    - assets/languages/js.png
    - assets/languages/kotlin.png
    - assets/languages/php.png
    - assets/languages/python.png
    - assets/languages/ruby.png
    - assets/languages/rust.png
    - assets/languages/sql.png
    - assets/languages/swift.png
    - assets/languages/text.png

    - assets/svg/notes.svg
    - assets/svg/settings.svg
    - assets/svg/ideas.svg
    - assets/svg/home.svg

  fonts:
    - family: Meem
      fonts:
        - asset: assets/fonts/meem/Meem-Bold.ttf
          weight: 700
    - family: Dana
      fonts:
        - asset: assets/fonts/dana/DanaFaNum-Bold.ttf
          weight: 700
        - asset: assets/fonts/dana/DanaFaNum-DemiBold.ttf
          weight: 600
        - asset: assets/fonts/dana/DanaFaNum-Medium.ttf
          weight: 500
        - asset: assets/fonts/dana/DanaFaNum-Regular.ttf
          weight: 400
        - asset: assets/fonts/dana/DanaFaNum-Light.ttf
          weight: 300
